name: public/tidy3d/python-client-daily-run

permissions:
  contents: read

jobs:
  update-lockfile:
    uses: ./.github/workflows/tidy3d-python-client-update-lockfile.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      run-workflow: true

  submodule-tests:
    uses: ./.github/workflows/tidy3d-python-client-submodules-test.yml
    with:
      run-workflow: true
